# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [3]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [4]:
print(np.__version__)
np.show_config()

1.24.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [5]:
### [your code here]
a = np.random.randint(1, 10, (2, 3, 5)) # 2x3x5 array, integers between 1–9


### 4. Print a.


In [29]:
### [your code here]
print(a)
print(a.shape)

[[[8 7 3 6 2]
  [6 8 7 5 6]
  [8 1 3 8 6]]

 [[4 8 4 6 1]
  [9 1 5 2 4]
  [9 6 7 3 9]]]
(2, 3, 5)


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [30]:
### [your code here]
b = np.ones((5,2,3))


### 6. Print b.


In [38]:
### [your code here]
print(b)

print(b.shape)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
(5, 2, 3)



### 7. Do a and b have the same size? How do you prove that in Python code?


In [39]:
### [your code here]
print(a.shape == b.shape)

False



### 8. Are you able to add a and b? Why or why not?


In [40]:
### [your code here]

# No, as they have different shapes (2,3,5) and (5,2,3) .
# sum = a + b



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [43]:
### [your code here]
c = np.transpose(b, (1, 2, 0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
### [your code here]

# a and c can be added because they have the same shape: (2, 3, 5).
# NumPy adds them element by element.

d = a + c

display(d)

array([[[ 9.,  8.,  4.,  7.,  3.],
        [ 7.,  9.,  8.,  6.,  7.],
        [ 9.,  2.,  4.,  9.,  7.]],

       [[ 5.,  9.,  5.,  7.,  2.],
        [10.,  2.,  6.,  3.,  5.],
        [10.,  7.,  8.,  4., 10.]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
### [your code here]

# Differences:
# The difference in data type is due to the fact that the c was created through np.ones() that defaults to float. 
# So, d is a float array.

# Relation:
# Each element in d = the corresponding value in a + 1.  {d = a + 1} 


print(a)
print("\n")
print(d)

[[[8 7 3 6 2]
  [6 8 7 5 6]
  [8 1 3 8 6]]

 [[4 8 4 6 1]
  [9 1 5 2 4]
  [9 6 7 3 9]]]


[[[ 9.  8.  4.  7.  3.]
  [ 7.  9.  8.  6.  7.]
  [ 9.  2.  4.  9.  7.]]

 [[ 5.  9.  5.  7.  2.]
  [10.  2.  6.  3.  5.]
  [10.  7.  8.  4. 10.]]]



### 12. Multiply a and c. Assign the result to e.


In [46]:
### [your code here]

e = a * c
print(e)

[[[8. 7. 3. 6. 2.]
  [6. 8. 7. 5. 6.]
  [8. 1. 3. 8. 6.]]

 [[4. 8. 4. 6. 1.]
  [9. 1. 5. 2. 4.]
  [9. 6. 7. 3. 9.]]]




### 13. Does e equal to a? Why or why not?


In [52]:
### [your code here]

# They are equal because c contains ones, so multiplying by c leaves a unchanged.
# a and e have the same values element by element.
print(a == e) 

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [48]:
### [your code here]

d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max, d_min, d_mean)

10.0 2.0 6.4



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [49]:
### [your code here]

f = np.empty((2,3,5))




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [ ]:
### [your code here]
for index, value in np.ndenumerate(d):
    if value == d_min:
        f[index] = 0
    elif value < d_mean:
        f[index] = 25
    elif value == d_mean:
        f[index] = 50
    elif value < d_max:
        f[index] = 75
    elif value == d_max:
        f[index] = 100





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [51]:
### [your code here]
print(d)
print("\n")
print(f)

# min: 2.0 || mean: 6.4 || max: 10.0

[[[ 9.  8.  4.  7.  3.]
  [ 7.  9.  8.  6.  7.]
  [ 9.  2.  4.  9.  7.]]

 [[ 5.  9.  5.  7.  2.]
  [10.  2.  6.  3.  5.]
  [10.  7.  8.  4. 10.]]]


[[[ 75.  75.  25.  75.  25.]
  [ 75.  75.  75.  25.  75.]
  [ 75.   0.  25.  75.  75.]]

 [[ 25.  75.  25.  75.   0.]
  [100.   0.  25.  25.  25.]
  [100.  75.  75.  25. 100.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [28]:
### [your code here]